version: '2.17.3'

# Things to do on the docker compose
# TODO Build services
# TODO Assign static ips to each service
# TODO Send the yaml configurations
# TODO Execute the command that starts the desired service inputing the -c with the desired yaml from the volume
# TODO bash script with the ogstun configuration for the user communication

#Setting up the common range of ips used by all the containers (5g services and webui)
networks:
  common_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 192.168.0.0/24


# Set up of all the services needed
services:
  amf:
    image: registry.gitlab.bsc.es/ppc/software/open5gs/open5gs:latest
    networks:
      common_network:
        ipv4_address: 192.168.0.10
    volumes:
      - ./open5gs/config/:/open5gs/install/etc/open5gs
    devices:
      - "/dev/net/tun:/dev/net/tun"

    command: bash -c "./open5gs/install/bin/open5gs-amfd &&
             tail -f /open5gs/install/var/log/open5gs/amf.log &&
             cd open5gs/webui/ && 
             npm run dev"

  gnb:
    image: registry.gitlab.bsc.es/ppc/software/open5gs/ueransim:latest
    networks:
      common_network:
        ipv4_address: 192.168.0.11
    volumes:
      - ./ueransim/config/:/UERANSIM/config

    command: ./UERANSIM/build/nr-gnb -c /UERANSIM/config/open5gs-gnb.yaml

  ue:
    image: registry.gitlab.bsc.es/ppc/software/open5gs/ueransim:latest
    networks:
      common_network:
        ipv4_address: 192.168.0.12
    volumes:
      - ./ueransim/config/:/UERANSIM/config

    command: ./UERANSIM/build/nr-ue -c /UERANSIM/config/open5gs-ue.yaml